version: "3.4"

volumes:
  postgres-storage:
services:
  db:
    container_name: exchange_db
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./pkg/conf/dev.env
    restart: unless-stopped

  app:
    container_name: exchange_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./pkg/conf/dev.env
      - ./pkg/conf/docker.env
    ports:
      - "4000:4000"
