openapi: 3.1.0
info:
  description: |
    # Introduction
    This API is documented in **OpenAPI 3.0 format**.

    This API the following operations:
    * Retrieve a list of available instruments
    * Retrieve a list of executed trades

    # Basics
    * API calls have to be secured with HTTPS.
    * All data has to be submitted UTF-8 encoded.
    * The reply is sent JSON encoded.
  title: OPEN OUTCRY API
  version: 1.0.0
servers:
- url: https://your.public.url
security:
- basicAuth: []
paths:
  /currencies:
    get:
      description: Returns list of available currencies
      operationId: getCurrencies
      responses:
        "200":
          content:
            application/json:
              schema:
                description: List of currencies supported by app
                items:
                  description: Currency of payment account
                  properties:
                    name:
                      description: ISO 4217 Currency symbol
                      example: USD
                    precision:
                      description: Currency precision as number of decimal points
                      example: 2
          description: currencies list
        "500":
          description: Error
      summary: currencies list
      tags:
      - currencies
  /instruments:
    get:
      description: Returns list of available instruments
      operationId: getInstruments
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  properties:
                    id:
                      format: uuid
                    name:
                      description: "Ticker-like name of the instrument. For monetary\
                        \ instruments, a currency pair is used."
                    base_currency:
                      description: ISO 4217 Currency symbol
                      example: USD
                    quote_currency:
                      description: ISO 4217 Currency symbol
                      example: USD
                    enabled:
                      description: Availability for trading
          description: instruments list
        "500":
          description: Error
      summary: instrument list
      tags:
      - instruments
  /order_books/{instrument_name}:
    get:
      description: Return an order book for an instrument
      operationId: getOrderBook
      parameters:
      - explode: false
        in: path
        name: instrument_name
        required: true
        schema:
          description: "Ticker-like name of the instrument. For monetary instruments,\
            \ a currency pair is used."
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getOrderBook_200_response'
          description: order book
        "500":
          description: Error
      summary: get order books
      tags:
      - order_books
  /trades:
    get:
      description: Returns list of user's trades
      operationId: getTrades
      responses:
        "200":
          content:
            application/json:
              schema:
                description: List of executed trades
                items:
                  description: Execute trade
                  properties:
                    id:
                      format: uuid
          description: trades list
        "500":
          description: Error
      summary: trades list
      tags:
      - trades
  /trade_orders:
    get:
      description: Returns list of user's active trade orders
      operationId: getTradeOrders
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  properties:
                    id:
                      format: uuid
                    instrument:
                      description: "Ticker-like name of the instrument. For monetary\
                        \ instruments, a currency pair is used."
                    side:
                      enum:
                      - SELL
                      - BUY
                    timeInForce:
                      enum:
                      - GTC
                      - IOC
                      - FOK
                      - GTD
                      - GTT
                    status:
                      enum:
                      - OPEN
                      - REJECTED
                      - CANCELLED
          description: trades orders list
        "500":
          description: Error
      summary: trade order list
      tags:
      - trade_order
components:
  schemas:
    getOrderBook_200_response:
      example:
        sell: ""
        buy: ""
      properties:
        sell:
          items:
            properties:
              price: {}
              volume: {}
        buy:
          items:
            properties:
              price: {}
              volume: {}
  securitySchemes:
    basicAuth:
      scheme: basic
      type: http
