openapi: 3.1.0
info:
  description: |
    # Introduction
    This API is documented in **OpenAPI 3.0 format**.

    This API the following operations:
    * Retrieve a list of available instruments
    * Retrieve a list of executed trades

    # Basics
    * API calls have to be secured with HTTPS.
    * All data has to be submitted UTF-8 encoded.
    * The reply is sent JSON encoded.

  version: 1.0.0
  title: OPEN OUTCRY API

servers:
  - url: http://localhost:4000

# This API has no security
security: []

tags:
  - name: user
    description: User facing resources for management by a specific user of their accounts

  - name: public
    description: Public facing resources pertaining to exchange in general

  - name: admin
    description: Admin facing resources for exchange management

paths:
  # EXCHANGE OPERATIONS
  /currencies:
    $ref: ./endpoints/public/currencies.yaml
  /fxinstruments:
    $ref: ./endpoints/public/fx-instruments.yaml
  /instruments:
    $ref: ./endpoints/public/instruments.yaml
  /order-books/{instrument_name}:
    $ref: ./endpoints/public/order_books_by_instrument_name.yaml

  # USER OPERATIONS
  /book-orders/{trading_account_id}:
    $ref: ./endpoints/user/book_orders.yaml
  /payment-accounts/{app_entity_id}:
    $ref: ./endpoints/user/payment_accounts.yaml
  /trades/{trading_account_id}/id/{trade_id}:
    $ref: ./endpoints/user/trades_by_id.yaml
  /trades/{trading_account_id}:
    $ref: ./endpoints/user/trades.yaml
  /trade-orders/{trading_account_id}:
    $ref: ./endpoints/user/trade_orders.yaml
  /trade-orders/{trading_account_id}/id/{trade_order_id}:
    $ref: ./endpoints/user/trade_orders_by_id.yaml
  /trading-accounts/{trading_account_id}:
    $ref: ./endpoints/user/trading_account_by_id.yaml

  #  # ADMIN OPERATIONS
  /apps/{app_entity_id}:
    $ref: ./endpoints/admin/apps_by_id.yaml
  /apps:
    $ref: ./endpoints/admin/apps.yaml
  /apps/payments/{payment_id}:
    $ref: ./endpoints/admin/payments_by_id.yaml
  /apps/payments:
    $ref: ./endpoints/admin/payments.yaml
