name: Golang CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3

      - name: Start db
        uses: isbang/compose-action@v1.4.1
        with:
          down-flags: "--volumes"
          services: |
            db

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: make build

      - name: Test
        run: make test
